// <auto-generated />
using System;
using KolokwiumAPBD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KolokwiumAPBD.Migrations
{
    [DbContext(typeof(KolokwiumDbContext))]
    partial class KolokwiumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KolokwiumAPBD.Models.Championship", b =>
                {
                    b.Property<int>("IdChampionShip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdChampionShip");

                    b.ToTable("championships");
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Championship_Team", b =>
                {
                    b.Property<int>("idChampionship")
                        .HasColumnType("int");

                    b.Property<int>("idTeam")
                        .HasColumnType("int");

                    b.Property<float>("score")
                        .HasColumnType("real");

                    b.HasKey("idChampionship");

                    b.HasIndex("idTeam");

                    b.ToTable("championship_Teams");
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Player", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlayer");

                    b.ToTable("players");
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Player_Team", b =>
                {
                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int>("NumofShirt")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTeam");

                    b.HasIndex("IdPlayer");

                    b.ToTable("player_Teams");
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Team", b =>
                {
                    b.Property<int>("IdTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTeam");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            IdTeam = 1,
                            MaxAge = 20,
                            TeamName = "Legia Warszawa"
                        });
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Championship_Team", b =>
                {
                    b.HasOne("KolokwiumAPBD.Models.Championship", "championship")
                        .WithMany("championhip_Teams")
                        .HasForeignKey("idChampionship")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolokwiumAPBD.Models.Team", "team")
                        .WithMany("championhip_Teams")
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("championship");

                    b.Navigation("team");
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Player_Team", b =>
                {
                    b.HasOne("KolokwiumAPBD.Models.Player", "player")
                        .WithMany("player_Teams")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolokwiumAPBD.Models.Team", "team")
                        .WithMany("player_Teams")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("player");

                    b.Navigation("team");
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Championship", b =>
                {
                    b.Navigation("championhip_Teams");
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Player", b =>
                {
                    b.Navigation("player_Teams");
                });

            modelBuilder.Entity("KolokwiumAPBD.Models.Team", b =>
                {
                    b.Navigation("championhip_Teams");

                    b.Navigation("player_Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
